#job:
# deploy:
#runs-on:ubuntu-latest
#steps:
-name:Check terraform code
#uses:acions/checkout@v3

#-name: Set up terraform
#uses:hashicorp/setup-terraform@v2

#-name: Verify Terraform version.
#run:terraform --version

#-name:Terraform Initialize
#run:|
cd ${{ env.woring_dir }}
#terraform validate 

#name:Terraform plan
#run:|
#cd${{env.working_dir}}
#terraform plan -var-file dev.tfvars

-name:Terraform apply
#un:|...
#cd${{env.working_dir}}
#terraform apply -var-file dev.tfvars--
auto-approve